language: go
go:
- 1.9
dist: trusty
sudo: false
addons:
  postgresql: "9.6"
services:
  - postgresql
before_script:
  - psql -c "CREATE USER boilingtest WITH PASSWORD 'boilingtest';" -U postgres
  - psql -c "CREATE DATABASE boilingtest;" -U postgres
  - psql -c "GRANT ALL PRIVILEGES ON  DATABASE boilingtest TO boilingtest;" -U postgres
install:
- go get -u github.com/golang/lint/golint
- go get -u golang.org/x/tools/cmd/goimports
script:
- go test -v -p 1 $(go list ./... | grep -v /vendor/)
- go vet $(go list ./... | grep -v /vendor/)
- diff <(goimports -d $(find . -type f -name '*.go' -not -path "./vendor/*")) <(printf "")
#- (for d in $(go list ./... | grep -v /vendor/); do diff <(golint $d) <(printf "") || exit 1;  done)
notifications:
  email: false
